
services:
  pythonapp:
    container_name: pythonservice2
    # restart: always
    build: ./
    volumes:
      - ./logs:/app/logs
    command: python3 ./hi.py
    ports:
      - "5000:3000"
    # links:
    #   - mongodb

  # mongodb:
  #   container_name: dashboardDataBase
  #   image:  mongo
  #   command: mongod --port 27017
  #   ports:
  #     - '27017:27017'


#  docker-compose build   image creation with compose
# docker-compose up --build       start services
