version: '3.1'
services:
  pythonapp:
    container_name: pythonservice2
    # restart: always
    build: ./
    volumes:
      - ./logs:/app/logs
    command: python3 ./worker-mqtt.py
    ports:
      - "5000:3000"
    links:
      - mongodb

  flaskServer:
    container_name: flask-server
    build: ./
    command: python3 ./router.py
    ports:
      - "5000:3000"

  mongodb:
    container_name: dashboardDataBase
    image:  mongo
    command: mongod --port 27017
    ports:
      - '27017:27017'


#  docker-compose build   image creation with compose
# docker-compose up --build       start services
